name: zyraLobby
main: com.zyramc.lobby.Main
version: 1.0
description: Lobby plugin for ZyraMC
author: Neviizs

commands:
  build:
  fly:
  spawn:
  setspawn:
  resetspawn:
  setnpc:
  delnpc:
  removehugeitem: